### ISSUE TITLE
Hey all  Meeting List PDF Question

### ISSUE THREAD

**Issue by GCITechSC** [code4recovery/nyintergroup-pdf#1]
Trying to get in touch with Chris on this, but if anyone else can help with the below question, I'd greatly appreciate it.

Still learning here. I'm loving what TSML does for our website at aacolumbia.org

I have had the PDF generator, but pretty sure I am underutilizing it. I STILL haven't made a child theme (scares me a little).

Here's what I'm currently doing. Meetings get updated, I go to the Generator, generate new list, download, then update another place on our site where the download link is available by replacing the PDF that I've downloaded.

What I think I could do is make the hyperlink on the "Greater Columbia Intergroup Meeting List" link to this? But do I have the address correct?
www.aacolumbia.org/meetings/wp-content/uploads/meeting_list.pdf

Is that right?

Thanks for anyone's help!

**Comment by joshreisner** [comment]
This isn't the right place. This is a repository for a different PDF generator. You're asking a general WordPress question. Please ask on the TiAA forums.
